apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPIAMAuditLogConstraintV1
metadata:
  name: audit_log_all
  annotations:
    description: Checks that all services have all types of audit logs enabled.
    bundles.validator.forsetisecurity.org/healthcare-baseline-v1: security
spec:
  severity: medium
  match:
    ancestries:
      - "projects/**"
      - "folders/**"
    excludedAncestries: ["organizations/542139653104/folders/959676550738"]
  parameters:
    services:
      - "allServices"
    log_types:
      - "DATA_READ"
      - "DATA_WRITE"
      - "ADMIN_READ"
