# policies/constraints/tf_compute_address_internal_only.yaml
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: GCPCloudArmorRuleDescriptionConstraintV1
metadata:
  name: gcpcloudarmorruledescriptionconstraintv1
spec:
  severity: high
  match:
    addresses:
    - "**"
  parameters: {}
